#### Config for CB-Spider PoC ####

## Config for OpenStack ##
openstack:

  # OpenStack Credential Info
  domain_name: {domain_name}
  identity_endpoint: http://{ip}:5000/v3
  password: {password}
  project_id: {project_id}
  username: {username}
  region: {region}

  # OpenStack VM Deployment Info
  vm_name: {vm_name}
  image_id: {image_id}
  flavor_id: {flavor_id}
  network_id: {network_id}
  security_groups: {security_groups}
  keypair_name: {keypair_name}

  # OpenStack Test VM Info
  server_id: {server_id}

  image_info:
    name: mcb_custom_image.iso

  keypair_info:
    name: mcb-test-key

  security_group_info:
    name: mcb-test-security

  vnet_info:
    name: mcb-test-vnet

## Config for AZURE ##
azure:

  # Azure Credential Info
  client_id: {client_id}
  client_secret: {client_secret}
  tenant_id: {tenant_id}
  subscription_id: {subscription_id}

  # Azure VM Deployment Info
  location: {location}
  vm_size: {vm_size}
  image:
    publisher: {publisher}
    offer: {offer}
    sku: {sku}
    version: {version}
  os:
    compute_name: {compute_name}
    admin_username: {admin_username}
    admin_password: {admin_password}
  network:
    id: {id}

  # Azure Test VM Info
  group_name: {group_name}
  vm_name: {vm_name}

  image_info:
    group_name: {group_name}
    name: {name}

  public_ip:
    group_name: {group_name}
    name: {name}

  security_group:
    group_name: {group_name}
    name: {name}

  virtual_network:
    group_name: {group_name}
    name: {name}

  network_interface:
    group_name: {group_name}
    name: {name}


## Config for Cloudit ##
cloudit:

  # Cloudit Credential Info
  user_id: cloudit
  password: cloudit
  identity_endpoint: http://stg.cloudit.co.kr:9090
  auth_token: ddd8e54a5bac82eea3de7c347ff8a253d0dc563d
  tenant_id: tnt0008
  server_id: 7b35148e-b033-4749-a29e-12beddaebbfa


  # Cloudit VNet(Subnet) Info
  virtual_network:
    name: mcb-subnet-test2
    addr: 10.0.12.0
