#### Config for CB-Spider PoC ####

## Config for OpenStack ##

#openstack:
#  domain_name: {domain_name}
#  identity_endpoint: http://{ip}:5000/v3
#  password: {password}
#  project_id: {project_id}
#  username: {username}
#  region: {region}

openstack:

  # OpenStack Credential Info
  domain_name: {domain_name}
  identity_endpoint: http://{ip}:5000/v3
  password: {password}
  project_id: {project_id}
  username: {username}
  region: {region}

  # OpenStack VM Deployment Info
  vm_name: mcb-test-vm
  image_id: 3da11509-cf77-4101-a946-3ab8d4554dd0
  flavor_id: 2
  network_id: b0774ac8-3124-4d62-a07a-5cf32f6e3567
  security_groups: test-sg
  keypair_name: mcb-key

  # OpenStack Test VM Info
  server_id: 91c7546b-ad1e-4ce3-963d-099ad96145ba
