#### Config for CB-Spider PoC ####

## Config for OpenStack ##
openstack:

  # OpenStack Credential Info
  domain_name: {domain_name}
  # identity_endpoint: http://{ip}/identity/v3   # for devstak-queens
  identity_endpoint: http://{ip}:5000/v3
  password: {password}
  project_id: {project_id}
  username: {username}
  region: {region}

  # OpenStack VM Deployment Info
  vm_name: {vm_name}
  image_id: {image_id}
  flavor_id: {flavor_id}
  network_id: {network_id}
  security_groups: {security_groups}
  keypair_name: {keypair_name}

  # OpenStack Test VM Info
  server_id: {server_id}

  image_info:
    name: mcb_custom_image.iso

  keypair_info:
    name: mcb-test-key

  security_group_info:
    name: mcb-test-security

  vnet_info:
    name: mcb-test-vnet

## Config for AZURE ##
azure:


  # Azure Credential Info
  client_id: xxx
  client_secret: xxx
  tenant_id: xxx
  subscription_id: xxx

  # Azure VM Deployment Info
  location: koreacentral
  vm_size: Standard_B1ls
  image:
    publisher: Canonical
    offer: UbuntuServer
    sku: 16.04.0-LTS
    version: latest

  os:
    compute_name: mcb-test-vm
    admin_username: cbarista
    admin_password: xxx

  nic:
    id: /subscriptions/f1548292-2be3-4acd-84a4-6df079160846/resourceGroups/cb-resource-group/providers/Microsoft.Network/networkInterfaces/cb-nic

  # Azure Test VM Info
  group_name: cb-resource-group
  vm_name: vm-name

  image_info:
    group_name: cb-resource-group
    name: image-name

  public_ip:
    group_name: cb-resource-group
    name: ip_name

  security_group:
    group_name: cb-resource-group
    name: sec_name

  virtual_network:
    group_name: cb-resource-group
    name: vnet_name

  network_interface:
    group_name: cb-resource-group
    name: nic_name



aws:

  # AWS Credential Info
  aws_access_key_id: None
  aws_secret_access_key: None
  region: ap-northeast-2

  # AMI
  image_id: ami-047f7b46bd6dd5d84

  # EC2
  ec2_instance_id: i-04f1693f5e94c1c79
  base_name: mcloud-barista
  instance_type: t2.micro
#  key_name: mcloud-barista-keypair
  key_name: powerkimkeypair
  min_count: 1
  max_count: 1

  # Network
  subnet_id: subnet-c3b446ab
  security_group_id: sg-07ec42983dbc5e36e


## Config for Cloudit ##
cloudit:

  # Cloudit Credential Info
  identity_endpoint: http://localhost:9090
  user_id: xxx
  password: xxx
  tenant_id: test-tenant

  server_id: test-server-id
